# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('food_price', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='price of food item (Rs.)')),
                ('food_size', models.IntegerField(choices=[(0, 'half'), (1, 'full')], db_index=True, help_text='size of food item half/full', null=True)),
                ('food_type', models.IntegerField(choices=[(0, 'veg'), (1, 'Non_Veg')], db_index=True, help_text='type of food veg/non_veg', null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Cuisine')),
            ],
        ),
    ]
